export const recipes = [
  {
    name: "Spaghetti Carbonara",
    ingredients: ["spaghetti", "eggs", "pancetta", "parmesan cheese", "pepper"],
    dietary: ["gluten"],
    cuisine: "italian",
  },
  {
    name: "Vegetable Stir Fry",
    ingredients: [
      "broccoli",
      "carrots",
      "bell peppers",
      "soy sauce",
      "ginger",
      "garlic",
    ],
    dietary: ["vegan", "gluten-free"],
    cuisine: "chinese",
  },
  {
    name: "Chicken Tacos",
    ingredients: ["chicken", "taco shells", "lettuce", "tomato", "cheese"],
    dietary: [],
    cuisine: "mexican",
  },
  {
    name: "Chana Masala",
    ingredients: ["chickpeas", "tomatoes", "onions", "spices"],
    dietary: ["vegan", "gluten-free"],
    cuisine: "indian",
  },
  {
    name: "Margherita Pizza",
    ingredients: ["pizza dough", "tomato sauce", "mozzarella", "basil"],
    dietary: ["vegetarian"],
    cuisine: "italian",
  },
  {
    name: "Beef Burritos",
    ingredients: ["beef", "tortillas", "beans", "rice", "cheese"],
    dietary: [],
    cuisine: "mexican",
  },
  {
    name: "Paneer Butter Masala",
    ingredients: ["paneer", "tomatoes", "cream", "spices"],
    dietary: ["vegetarian"],
    cuisine: "indian",
  },
  {
    name: "Sweet and Sour Pork",
    ingredients: ["pork", "pineapple", "bell peppers", "sweet and sour sauce"],
    dietary: [],
    cuisine: "chinese",
  },
  {
    name: "Quinoa Salad",
    ingredients: ["quinoa", "cucumber", "tomato", "feta cheese", "olive oil"],
    dietary: ["vegetarian", "gluten-free"],
    cuisine: "mediterranean",
  },
  {
    name: "Falafel Wraps",
    ingredients: [
      "falafel",
      "tortilla wraps",
      "lettuce",
      "tomato",
      "tzatziki sauce",
    ],
    dietary: ["vegetarian"],
    cuisine: "mediterranean",
  },
  {
    name: "Tom Yum Soup",
    ingredients: ["shrimp", "mushrooms", "lemongrass", "lime", "chili"],
    dietary: ["gluten-free"],
    cuisine: "thai",
  },
  {
    name: "Pad Thai",
    ingredients: ["rice noodles", "chicken", "eggs", "peanuts", "bean sprouts"],
    dietary: ["gluten-free"],
    cuisine: "thai",
  },
  {
    name: "Lentil Soup",
    ingredients: ["lentils", "carrots", "celery", "tomato", "spices"],
    dietary: ["vegan", "gluten-free"],
    cuisine: "mediterranean",
  },
  {
    name: "Fish and Chips",
    ingredients: ["fish", "potatoes", "flour", "oil"],
    dietary: [],
    cuisine: "british",
  },
  {
    name: "Caesar Salad",
    ingredients: [
      "romaine lettuce",
      "croutons",
      "parmesan cheese",
      "caesar dressing",
    ],
    dietary: ["vegetarian"],
    cuisine: "american",
  },
  {
    name: "Egg Fried Rice",
    ingredients: ["rice", "eggs", "peas", "carrots", "soy sauce"],
    dietary: [],
    cuisine: "chinese",
  },
  {
    name: "Chicken Shawarma",
    ingredients: ["chicken", "pita bread", "lettuce", "tomato", "garlic sauce"],
    dietary: [],
    cuisine: "middle-eastern",
  },
  {
    name: "Greek Salad",
    ingredients: ["cucumber", "tomato", "feta cheese", "olives", "olive oil"],
    dietary: ["vegetarian", "gluten-free"],
    cuisine: "greek",
  },
  {
    name: "Vegan Burger",
    ingredients: [
      "vegan patty",
      "burger buns",
      "lettuce",
      "tomato",
      "vegan cheese",
    ],
    dietary: ["vegan"],
    cuisine: "american",
  },
  {
    name: "Pancakes",
    ingredients: ["flour", "milk", "eggs", "sugar", "baking powder"],
    dietary: ["vegetarian"],
    cuisine: "american",
  },
  {
    name: "Chicken Parmesan",
    ingredients: [
      "chicken breast",
      "parmesan cheese",
      "bread crumbs",
      "marinara sauce",
      "mozzarella",
    ],
    dietary: ["gluten"],
    cuisine: "italian",
  },
  {
    name: "General Tso's Chicken",
    ingredients: [
      "chicken",
      "soy sauce",
      "rice vinegar",
      "sugar",
      "cornstarch",
    ],
    dietary: [],
    cuisine: "chinese",
  },
  {
    name: "Beef Enchiladas",
    ingredients: ["beef", "enchilada sauce", "tortillas", "cheese"],
    dietary: [],
    cuisine: "mexican",
  },
  {
    name: "Palak Paneer",
    ingredients: ["spinach", "paneer", "onions", "tomatoes", "spices"],
    dietary: ["vegetarian"],
    cuisine: "indian",
  },
  {
    name: "Caprese Salad",
    ingredients: [
      "tomatoes",
      "mozzarella",
      "basil",
      "olive oil",
      "balsamic vinegar",
    ],
    dietary: ["vegetarian", "gluten-free"],
    cuisine: "italian",
  },
  {
    name: "Tacos Al Pastor",
    ingredients: ["pork", "pineapple", "taco shells", "onions", "cilantro"],
    dietary: [],
    cuisine: "mexican",
  },
  {
    name: "Dal Tadka",
    ingredients: ["lentils", "tomatoes", "onions", "spices"],
    dietary: ["vegan", "gluten-free"],
    cuisine: "indian",
  },
  {
    name: "Moussaka",
    ingredients: [
      "eggplant",
      "ground beef",
      "tomatoes",
      "onions",
      "bechamel sauce",
    ],
    dietary: [],
    cuisine: "greek",
  },
  {
    name: "Baklava",
    ingredients: ["phyllo dough", "nuts", "honey", "butter"],
    dietary: [],
    cuisine: "greek",
  },
  {
    name: "Sushi Rolls",
    ingredients: ["sushi rice", "nori", "fish", "cucumber", "avocado"],
    dietary: ["gluten-free"],
    cuisine: "japanese",
  },
  {
    name: "Teriyaki Chicken",
    ingredients: ["chicken", "soy sauce", "mirin", "sugar", "ginger"],
    dietary: [],
    cuisine: "japanese",
  },
];
